server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///ktp_db?useSSL=FALSE&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 13241324a
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#      路径


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


